// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://adgcrcfbsuwvegxrrrpf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFkZ2NyY2Zic3V3dmVneHJycnBmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYyNTM5NDgsImV4cCI6MjA2MTgyOTk0OH0.oNHSFwoLX1J-d-WXTMDEw_wS2f1WBoTJTkA_XNY1ngg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);